CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS weight_history CASCADE;
DROP TABLE IF EXISTS calorie_history CASCADE;

CREATE TABLE weight_history (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  date DATE DEFAULT CURRENT_DATE,
  weight DECIMAL(6, 2)
);

CREATE TABLE calorie_history (
  id SERIAL PRIMARY KEY,
  user_id INTEGER REFERENCES users(id),
  date DATE DEFAULT CURRENT_DATE,
  calories INTEGER
);